### ISSUE TITLE
Creating an Entity object with a sequence with 'X'

### ISSUE THREAD

**Issue by josemduarte** [ihmwg/ModelCIF#13]
I have this code snippet:

```python
    seq = "XATTHLL"
    model_e = modelcif.Entity(seq, description='Model subunit')
```
Which fails with `KeyError: 'X'`

The dictionary `LPeptideAlphabet._comps` indeed does not have 'X' but it has 'UNK' as a key instead. 

Is the `Entity` constructor supposed to behave like that when sequence contains `X`? If so, what would be the right way to construct an `Entity` with an `UNK` aminoacid?

**Comment by benmwebb** [comment]
Yes, this is as designed. The first argument to `Entity` is a sequence of `ChemComp` objects or codes. When all your codes are one-letter, sure, you can get away with using a string. But in this case they are not (as far as mmCIF is concerned, the code for UNK is UNK; only the canonical code is "X"). So you could use a list or tuple instead, e.g. `seq = ['UNK', 'A', 'T', 'T', 'H', 'L', 'L']`.

If you're sure that in your application X always means UNK, you could map it with a simple one-liner as we do for ModBase models: https://github.com/salilab/modbase_utils/blob/0.4/modbase_pdb_to_cif.py#L108

Alternatively you could provide your own `Alphabet` subclass to the `Entity` constructor, e.g.

```
class MyAlphabet(ihm.LPeptideAlphabet):
    _comps = ihm.LPeptideAlphabet._comps.copy()
    _comps['X'] = _comps['UNK']

seq = "XATTHLL"
model_e = modelcif.Entity(seq, description='Model subunit', alphabet=MyAlphabet)
```

**Comment by josemduarte** [comment]
Wonderful, thanks for the fast reply! Will do that.
