### ISSUE TITLE
_ma_target_ref_db_details.gene_name item type change

### ISSUE THREAD

**Issue by drlemmus** [ihmwg/ModelCIF#16]
When parsing AlphaFoldDB entries we found that some cases have a value for _ma_target_ref_db_details.gene_name that is incompatible with the item type as defined in ModelCIF (code). Examples are:
AF-A0A0M3KKW8-F1
AF-H6SHY4-F1
AF-O78126-F1
AF-Q6RH29-F1
AF-Q6RH28-F1
AF-Q6RH30-F1
AF-Q6XEC0-F1

We reported this issue to to the helpdesk of AlphaFoldDB who answered:
//
The pipeline for predictions of AlphaFold, retrieves metadata from UniProt.
Since, the mmCIF files were created by Google Deepmind, we can't modify the
content of the field ourselves.

We recommend you to please reach out to  https://pdb-dev.wwpdb.org/ to look
into the updating regex for this field as it does accept whitespaces.
//
Rather than changing the regex for the type "code", perhaps the type for _ma_target_ref_db_details.gene_name can be set to "text" or another type that is compatible with Uniprot entries that have a gene name (from the 'GN' record I suppose) with spaces in it.

**Comment by benmwebb** [comment]
e.g. https://www.alphafold.ebi.ac.uk/entry/H6SHY4 contains

```
_ma_target_ref_db_details.gene_name                    "celH or egH"
```

while https://www.alphafold.ebi.ac.uk/entry/O78126 contains

```
_ma_target_ref_db_details.gene_name                    "MHC class I HLA-A"
```
