### ISSUE TITLE
Extend enumerations for _ma_associated_archive_file_details.file_format

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/ModelCIF#17]
Aim: add support for images as accompanying data

Allowed values to add to _ma_associated_archive_file_details.file_format:
- "png" for PNG files
- "jpg" for JPEG files

Background info: PNG was observed in a recent ModelArchive deposition. Suggestion to add JPEG is to cover both the most popular lossless and the most popular lossy image format.

**Comment by brindakv** [comment]
Addressed in https://github.com/ihmwg/ModelCIF/pull/25.
