### ISSUE TITLE
Extend ma_target_ref_db_details for multiple links

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/ModelCIF#18]
To support cases where one entity should link to multiple entries in a target DB (e.g. for chimeric proteins or due to multiple entries with identical sequences), `ma_target_ref_db_details` should include "db_code" and/or "db_accession" to the category key.

Additionally, an additional, optional `is_primary` boolean item is to be added to `ma_target_ref_db_details` to allow marking the main input used for modelling.

Side note: ModelCIF files used in ModBase already contain multiple UniProt links (e.g. for [Q12321](https://modbase.compbio.ucsf.edu/modbase-cgi/model_search.cgi?databaseID=Q12321)) and hence are technically invalid according to the current dictionary.

**Comment by gtauriello** [comment]
@brindakv it will be good if this could be fixed soon since we need this feature to properly write ModelCIF files for our SWISS-MODEL Repository. I suppose if #21 gets done early November, this can easily be added there as well?

**Comment by brindakv** [comment]
Addressed in https://github.com/ihmwg/ModelCIF/pull/25.
