### ISSUE TITLE
per-atom PAE scores

### ISSUE THREAD

**Issue by aozalevsky** [ihmwg/ModelCIF#20]
[`models.qa_metric.LocalPairwise`](https://python-modelcif.readthedocs.io/en/latest/qa_metric.html#modelcif.qa_metric.LocalPairwise) is defined on the per-residue level, but as @arogozhnikov explained in https://github.com/chaidiscovery/chai-lab/issues/52, they estimate per-atom PAEs for ligands and non-canonical amino acids/nucleotides (atom vs residue (for canonical polymers) and atom vs atom for ligands and non-canonical residues). It would be nice if we could extend the `qa_metric.LocalPairwise` definition.

**Comment by gtauriello** [comment]
I created a new issue at #21 which should cover this case additionally to all other quality estimates introduced with AF3. If you think that #21 captures everything needed for https://github.com/chaidiscovery/chai-lab/issues/52 I think we can close this one as redundant?

**Comment by aozalevsky** [comment]
sure
