### ISSUE TITLE
 _ma_template and `branched` entities

### ISSUE THREAD

**Issue by bienchen** [ihmwg/ModelCIF#22]
Templates from entities of type branched can not be marked in `_ma_template_details`. `_ma_template_details.template_entity_type` is missing the type `branched` and should be added. There is also no corresponding table for branched templates as we have `_ma_template_non_poly` for non-polymer templates. I think we should get such a table for type branched.

**Comment by brindakv** [comment]
Addressed in https://github.com/ihmwg/ModelCIF/pull/25.
