### ISSUE TITLE
Fix key in _ma_model_list

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/ModelCIF#23]
As discussed in other meetings, there is an issue with _ma_model_list since the primary key is [ordinal_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.ordinal_id.html) but everything points to [model_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_id.html). The possible solutions are to either move the primary key to model_id and deprecate ordinal_id or move parent-child relations to ordinal_id and deprecate model_id.

Practically the situation for current ModelCIF files (in ModelArchive, AlphaFold DB, AlphaPulldown, D-I-TASSER, ModBase and SWISS-MODEL) and tool support ([python-modelcif](https://github.com/ihmwg/python-modelcif)) is as follows:

- Nobody has yet used ModelCIF with multiple models in the same file or with multiple groups of models. In all examples, ordinal_id and model_id (and model_group_id) are identical.
- The dumper for python-modelcif, assigns model_id numbering models within the same group and can hence produce non-unique model_ids if multiple groups are in the list (see [example in tests](https://github.com/ihmwg/python-modelcif/blob/e92bb5b879cfff09fc62a686c8ebe7524eed71f4/test/test_dumper.py#L444))

Suggested solution:

1. Change all child data items of [_ma_model_list.model_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_id.html) to be child data items of ordinal_id instead.
2. Make [_ma_model_list.model_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_id.html) non-mandatory and change description to match how it is used in python-modelcif: "An identifier for the structural model within a model group. If the models do not need to be grouped into collections, this can be dropped or set to be the same as ordinal_id."
3. Change last sentence of description of [_ma_model_list.model_group_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_group_id.html) to: "If the models do not need to be grouped into collections, this can be dropped or set to be the same as ordinal_id."

**Comment by benmwebb** [comment]
>   Nobody has yet used ModelCIF with multiple models in the same file or with multiple groups of models. In all examples, ordinal_id and model_id (and model_group_id) are identical.

That's not quite true. ModBase does support multiple models in one file if you select multiple sequences in the Sequence Overview (e.g. https://modbase.compbio.ucsf.edu/modbase-cgi/model_search.cgi?dataset=dengue) and then request coordinate files in mmCIF format. But you'll get each model in a separate data block.

>  The dumper for python-modelcif, assigns model_id numbering models within the same group and can hence produce non-unique model_ids if multiple groups are in the list (see [example in tests](https://github.com/ihmwg/python-modelcif/blob/e92bb5b879cfff09fc62a686c8ebe7524eed71f4/test/test_dumper.py#L444))

python-modelcif uses python-ihm to assign model IDs. They are globally unique. You can see duplicate model IDs in the output (as above) if a given model is placed in multiple groups, but there are not multiple models with the same ID.

**Comment by gtauriello** [comment]
Ok in that case I would suggest that we deprecate model_id altogether and disallow duplicated models to show up in ma_model_list. For the dictionary this means (updated suggestion compared to above):

1. Change all child data items of [_ma_model_list.model_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_id.html) to be child data items of ordinal_id instead.
2. Make [_ma_model_list.model_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_id.html) non-mandatory and change description to: "A unique identifier for the structural model being deposited. Was practically a duplicate of ordinal_id and has been deprecated with dictionary version 1.4.7."
3. Change description of [_ma_model_list.ordinal_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.ordinal_id.html) to: "A unique identifier for the structural model being deposited."
4. Change last sentence of description of [_ma_model_list.model_group_id](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_model_list.model_group_id.html) to: "If the models do not need to be grouped into collections, this can be dropped or set to be the same as ordinal_id."

**Comment by brindakv** [comment]
In addition to the changes discussed above, I also suggest the following. 

1. Deprecate `_ma_model_list.model_group_id` and `_ma_model_list.model_group_name`
2. Add `ma_model_group`, `ma_model_group_link`, `ma_model_representative`

The changes will allow for many-to-many relationships between models and model groups and follow definitions similar to IHMCIF. 

All updates are implemented in https://github.com/ihmwg/ModelCIF/pull/25 but can be rolled back if needed.

**Comment by gtauriello** [comment]
Ok. Sounds reasonable. I will check in detail in #25 . One related comment though: the examples about `_ihm_model_list` in https://github.com/ihmwg/IHMCIF/blob/master/dictionary_documentation/documentation.md seem to be outdated as they use `_ihm_model_list.model_group_id` and `_ihm_model_list.model_group_name`...

**Comment by brindakv** [comment]
Thanks for pointing out the outdated documentation in IHMCIF. We have not updated/maintained it after IHMCIF was included in https://mmcif.wwpdb.org/dictionaries/mmcif_ihm_ext.dic/Index/. Perhaps we should remove it completely.
