### ISSUE TITLE
Missing mmCIF categories/items in ModelCIF

### ISSUE THREAD

**Issue by gtauriello** [ihmwg/ModelCIF#24]
Observation from validating example output from AlphaFold3 ([AF3_fold_test_fold_job_number_one_model_0.cif.gz](https://github.com/user-attachments/files/17776417/AF3_fold_test_fold_job_number_one_model_0.cif.gz); for the unlikely case that this is further shared please beware of the [output-terms-of-use](https://alphafoldserver.com/output-terms)):

_struct_conn.pdbx_role and _pdbx_branch_scheme are used which exist in mmCIF but not in ModelCIF. I assume that this is because we merge the ModelCIF extension with an old version of mmCIF? If so, this should be updated so that ModelCIF also includes those categories/items.

As a side note, here are my additional observations when validating the AF3 output:

- The mandatory _pdbx_nonpoly_scheme.ndb_seq_num item is missing
- The same entity can be listed multiple times (instead of having multiple asym_id mapped to same entity in _struct_asym).
- Unclear: is it ok to have non-polymer entities without _pdbx_entity_nonpoly? In their files, they only have _pdbx_nonpoly_scheme.

**Comment by brindakv** [comment]
Addressed in https://github.com/ihmwg/ModelCIF/pull/25.
