### ISSUE TITLE
Update _ma_data_ref_db.name definition

### ISSUE THREAD

**Issue by brindakv** [ihmwg/ModelCIF#9]
Make `_item_type.code` of [_ma_data_ref_db.name](https://mmcif.wwpdb.org/dictionaries/mmcif_ma.dic/Items/_ma_data_ref_db.name.html) less restrictive to allow for `ColabFold DB`.

**Comment by gtauriello** [comment]
@brindakv is there any update on this? We are almost done with a large set of ColabFold-based files, but currently they won't validate due to the "ColabFold DB" name used.

**Comment by brindakv** [comment]
@gtauriello I have updated the dictionary to be less restrictive for `_ma_data_ref_db.name`.
